### ISSUE TITLE
Slideshow Feature

### ISSUE THREAD

**Issue by metalshreds** [mykle1/MMM-EyeCandy#1]
Thanks for the great module! I was wondering if there was a way to display a slideshow of images as opposed to only one.

**Comment by mykle1** [comment]
Sorry I didn't see this till just now. I am looking into that very feature right now. Actually, I was going to make an EZSlideshow module, so when I do that, I'll add the slideshow feature to EyeCandy. Don't know when I'll get to it but thanks for your interest and idea!

Contact me in the forum if need be. I don't really look in here

**Comment by dennisklad** [comment]
Hi from the future! Is this possible to combine multiple images and displaying one each day?
