### ISSUE TITLE
New Feature Suggestion: Specify multiple styles

### ISSUE THREAD

**Issue by majurgens** [mykle1/MMM-EyeCandy#10]
The suggestion is to allow multiple styles to be specified in a single Style: specification and then displayed in the single module position in carousel fashion.
Perhaps, a comma delimited list that accepts
a) single numbers
b) ranges eg 10-13
eg 1,4,5,10-11,23-45,12

An additional parameter the control the transition time would be required.

I know the same result can be achieved using existing carousel modules but this would significantly simplify the configuration

**Comment by mykle1** [comment]
I don't have any plans to modify it. I'm really rather busy with other things (and life). Feel free to fork the repo and make the addition and send a PR to me, thanks.

**Comment by majurgens** [comment]
Can you please explain how to do a PR?

**Comment by mykle1** [comment]
PR = Pull request
First you would have to fork the repo - https://docs.github.com/en/github/getting-started-with-github/fork-a-repo
Then make your changes to your fork.
Then send the PR - https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork

**Comment by websterjazz** [comment]
Hi.. I am looking at something similar to what @majurgens is suggested.... Any update?
