### ISSUE TITLE
Image list barely usable

### ISSUE THREAD

**Issue by Dubidubiduu** [mykle1/MMM-EyeCandy#14]
I tried a few of your images. But copy pasting them to my browser by hand was boring.

Ideas:
- Script to download them to a folder, so I can have a look at them.
-  Very small comment after the lines to I know what I'm gonna see (for future links obvlsy.)

**Comment by mykle1** [comment]
I have a lot of modules but cannot maintain them all without help from users. Feel free to send me a PR with the issues you mentioned corrected. I'd really appreciate it.
