### ISSUE TITLE
This module seems to block 'Updatenotification' (default) module

### ISSUE THREAD

**Issue by smowk** [mykle1/MMM-EyeCandy#3]
Hi,

Apparently, this module will not allow the default updatenotification module to show up.
It doesn't matter where I set this module's position, the update will not show up; I'm using the default configuration.

I realized the problem might be related to this module after seeing this on the MMM-Remote-Control interface:

![no_updates](https://user-images.githubusercontent.com/36511888/47212712-a5396e80-d3a1-11e8-8365-7b29e2d298e1.png)

If I remove this module from the config, Updatenotification is no longer blocked.
I tested with more random modules, and the only one that is affected is the update notification default module.

Thank you

**Comment by mykle1** [comment]
Yes, I see. I don't use the updatenotification module so I never noticed this behavior. Thanks for bringing that to my attention. I'll see if I can fix that

**Comment by mykle1** [comment]
I'm closing this issue because Eye-Candy does not block the updateNotification module as you can see by this image.

https://upload-assets.vice.com/files/2016/12/19/1482167674giphy__3_.gif?seed=Sat%20Feb%2009%202019%2023:02:39%20GMT-0500%20(EST)
