### ISSUE TITLE
Giphy

### ISSUE THREAD

**Issue by swvalenti194** [mykle1/MMM-EyeCandy#5]
Sir, is it possible to rotate through several gifs?  I can use one url from giphy but when I try and add a second using ,'https://sample.com ', it doesn't work.

**Comment by mykle1** [comment]
You can only use one url at a time at the moment. The url must be direct to an image file, not a web page. I might look into implementing that some time in the future but I have no immediate plans to do so. Feel free to fork the repo and make changes. You can then send a PR for approval. Have fun
