### ISSUE TITLE
Not an issue.. please help then delete right away

### ISSUE THREAD

**Issue by hco125** [mykle1/MMM-EyeCandy#6]
@mykle1 

How on Earth can I send a message to you (or another module developer) for a small question about your module that is not necessarily an issue? I have been submitting issues on other modules for things like this because I have looked everywhere for a method to send developers private messages.

I am sorry for creating an "issue" to get this question answered. Please feel free to close it right away.

**Comment by mykle1** [comment]
Just hover over my avatar/picture on any of my  posts on the forum and click on the Chat button when the window opens.
