### ISSUE TITLE
no background

### ISSUE THREAD

**Issue by chassain** [mykle1/MMM-EyeCandy#7]
Hello mykle,

It's not really a issue, just an information for users. I like your module but i have looking to adapt your module with the module backgroud. It's important to say that users can have animated gif without background. Just add this in eyecandy.js. For example : 

            '100':`` 'https://3.bp.blogspot.com/-PWKHewX20Qk/W7u2WBX1dRI/AAAAAAAAArs/MoTp4utMcggCxvmCQkNhHSEyg6dPu7H3gCLcBGAs/s200/Earth.gif',
            '200': 'https://media0.giphy.com/media/yo1whaKkz38ME/giphy.webp?cid=ecf05e475d7a28e4409a759fe138783e35fe93754f28de52&rid=giphy.webp',
            '300': 'https://media3.giphy.com/media/CIjXMxobcEnkI/giphy.gif?cid=ecf05e47d1f8dbd2e0848f52a7aeb39b6467937d25a9633a&rid=giphy.gif',

Have a good day

**Comment by mykle1** [comment]
This is not an issue with my module
