### ISSUE TITLE
Stops working after a little while until reboot

### ISSUE THREAD

**Issue by fallenbuddhist** [mykle1/MMM-EyeCandy#9]
First, I love this module - thank you. 

However, I have been noticing that this module stops working while others appear unaffected (ruling out network connectivity issues also manually). Upon restarting MM it works again. Have you seen this issue before?

**Comment by mykle1** [comment]
I have not. How does it stop working?The image no longer appears?

Are any errors reported in the terminal or console of dev tools when this happens?

Thank you for your kind words

**Comment by mykle1** [comment]
I assume you worked it out
